Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [1]:
import numpy as np

In [3]:
array_1d = np.random.randint(10, 100, 50)
print(array_1d)

[98 35 71 19 19 35 52 43 52 47 92 76 29 15 43 22 15 55 85 30 72 12 56 90
 39 41 35 24 92 53 83 25 90 30 51 17 69 79 35 19 19 42 76 92 15 32 77 57
 75 69]


In [ ]:
array_1d[4::5] #empezamos en la 5 posicion mult.de 5


array([19, 47, 43, 30, 39, 53, 51, 19, 15, 69])

Crea un array 1D con 30 valores aleatorios del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [13]:
array2_1d = np.random.randint(1, 21, 30)
print(array2_1d)

[ 6  8 13 10 18  1 20 20 16 12 11 19  7  6 15  5 15  1  8 18 16  8  6  1
 19 11  6 17 13 15]


In [ ]:
array2_1d[0::2] #impares (pares desde 0 ??)

array([ 6, 13, 18, 20, 16, 11,  7, 15, 15,  8, 16,  6, 19,  6, 13])

In [11]:
len(array2_1d)

30

2. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [ ]:
array_2d = np.random.random_sample( (4,6) dtype=float)
print(array_2d)

In [32]:
array_2d = np.random.rand(4,6)
print(array_2d)
array_2dd = np.round(array_2d, 2)
print(array_2dd)
array_2dd[-1]


[[0.26410604 0.83977299 0.61004047 0.27256138 0.26640679 0.58486288]
 [0.80710798 0.52578365 0.58236192 0.59350276 0.95986889 0.60792361]
 [0.22737376 0.78791867 0.81286251 0.0636656  0.83133387 0.05451327]
 [0.29408057 0.56447115 0.07842851 0.85642691 0.57766817 0.68667236]]
[[0.26 0.84 0.61 0.27 0.27 0.58]
 [0.81 0.53 0.58 0.59 0.96 0.61]
 [0.23 0.79 0.81 0.06 0.83 0.05]
 [0.29 0.56 0.08 0.86 0.58 0.69]]


array([0.29, 0.56, 0.08, 0.86, 0.58, 0.69])

In [56]:
array_2d + np.random.randint(1,99,(4,6))

array([[30.26410604,  9.83977299, 33.61004047, 30.27256138, 48.26640679,
        34.58486288],
       [78.80710798,  9.52578365, 90.58236192, 50.59350276, 91.95986889,
        62.60792361],
       [13.22737376,  9.78791867, 80.81286251, 59.0636656 , 29.83133387,
        13.05451327],
       [10.29408057, 59.56447115, 94.07842851, 17.85642691, 35.57766817,
        58.68667236]])

bidimensional_red = np.round(bidimensional, 2)


Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [28]:
array_3d= np.random.rand(2,3,5)
print(array_3d)
array_3dd = np.round(array_3d, 1)
print(array_3dd)


[[[0.11825303 0.29075342 0.84023771 0.72356319 0.89339526]
  [0.37467151 0.31846735 0.56319417 0.5287858  0.08738397]
  [0.1576205  0.19794926 0.86549376 0.74120833 0.04082824]]

 [[0.62579336 0.61852034 0.2876934  0.04975639 0.45667877]
  [0.53922441 0.5652684  0.71911313 0.06840633 0.72785339]
  [0.78580235 0.69189798 0.13756206 0.72442522 0.41693296]]]
[[[0.1 0.3 0.8 0.7 0.9]
  [0.4 0.3 0.6 0.5 0.1]
  [0.2 0.2 0.9 0.7 0. ]]

 [[0.6 0.6 0.3 0.  0.5]
  [0.5 0.6 0.7 0.1 0.7]
  [0.8 0.7 0.1 0.7 0.4]]]


Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

Si el valor del array es igual que la media, se reemplaza por "A".

Si el valor del array es mayor que la media, se reemplaza por "B".

Si el valor del array es menor que la media, se reemplaza por "C".

Si el valor es igual que el máximo, se reemplaza por "D".

Si el valor es igual que el mínimo, se reemplaza por "E".

In [34]:
array2_3d= np.empty((2,3,5))
print(array2_3d)

[[[0.1 0.3 0.8 0.7 0.9]
  [0.4 0.3 0.6 0.5 0.1]
  [0.2 0.2 0.9 0.7 0. ]]

 [[0.6 0.6 0.3 0.  0.5]
  [0.5 0.6 0.7 0.1 0.7]
  [0.8 0.7 0.1 0.7 0.4]]]


In [ ]:
np.mean(array2_3d)

0.4666666666666666

In [41]:
np.where(array2_3d == 0.4, "A", array2_3d)

array([[['0.1', '0.3', '0.8', '0.7', '0.9'],
        ['A', '0.3', '0.6', '0.5', '0.1'],
        ['0.2', '0.2', '0.9', '0.7', '0.0']],

       [['0.6', '0.6', '0.3', '0.0', '0.5'],
        ['0.5', '0.6', '0.7', '0.1', '0.7'],
        ['0.8', '0.7', '0.1', '0.7', 'A']]], dtype='<U32')

In [43]:
np.where(array2_3d > 0.4, "B", array2_3d)

array([[['0.1', '0.3', 'B', 'B', 'B'],
        ['0.4', '0.3', 'B', 'B', '0.1'],
        ['0.2', '0.2', 'B', 'B', '0.0']],

       [['B', 'B', '0.3', '0.0', 'B'],
        ['B', 'B', 'B', '0.1', 'B'],
        ['B', 'B', '0.1', 'B', '0.4']]], dtype='<U32')

In [44]:
np.where(array2_3d < 0.4, "C", array2_3d)

array([[['C', 'C', '0.8', '0.7', '0.9'],
        ['0.4', 'C', '0.6', '0.5', 'C'],
        ['C', 'C', '0.9', '0.7', 'C']],

       [['0.6', '0.6', 'C', 'C', '0.5'],
        ['0.5', '0.6', '0.7', 'C', '0.7'],
        ['0.8', '0.7', 'C', '0.7', '0.4']]], dtype='<U32')

In [45]:
np.max(array2_3d)

0.9

In [46]:
np.where(array2_3d == 0.9, "D", array2_3d)

array([[['0.1', '0.3', '0.8', '0.7', 'D'],
        ['0.4', '0.3', '0.6', '0.5', '0.1'],
        ['0.2', '0.2', 'D', '0.7', '0.0']],

       [['0.6', '0.6', '0.3', '0.0', '0.5'],
        ['0.5', '0.6', '0.7', '0.1', '0.7'],
        ['0.8', '0.7', '0.1', '0.7', '0.4']]], dtype='<U32')

In [47]:
np.min(array2_3d)

0.0

In [48]:
np.where(array2_3d == 0.0, "E", array2_3d)

array([[['0.1', '0.3', '0.8', '0.7', '0.9'],
        ['0.4', '0.3', '0.6', '0.5', '0.1'],
        ['0.2', '0.2', '0.9', '0.7', 'E']],

       [['0.6', '0.6', '0.3', 'E', '0.5'],
        ['0.5', '0.6', '0.7', '0.1', '0.7'],
        ['0.8', '0.7', '0.1', '0.7', '0.4']]], dtype='<U32')

In [ ]:
Funciones Aritméticas y Estadísticas:
Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [53]:
ele = np.round((np.random.rand(2, 3, 5)), 1)
ele

array([[[0.1, 0.5, 0.3, 0.8, 0.1],
        [0.8, 0.7, 0.7, 0.2, 0.6],
        [0.1, 0.5, 0.8, 0.6, 0.5]],

       [[0.5, 0.1, 0.3, 0.9, 0.2],
        [0.2, 0.3, 0.3, 0.2, 0.1],
        [0.7, 0.1, 1. , 0.5, 0.5]]])

Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.